### ISSUE TITLE
Change Message Processing to a Output Column Handling

### ISSUE THREAD

**Issue by greifentor** [greifentor/service-monitor#3]
Replace the "message" attribute in the configuration by a an "output" structure like:
```
    output:
    - columns:
      - name: name
        width: 20
        align: LEFT
        content: ${name}
```
The fields are used for:
- output > is the name for the ouput sektion.
- columns > a list of column definitions.
- name > the name of the column.
- width > the column width.
- align > the alignment of the columns content (possible values: "RIGHT", "LEFT", "CENTER").
- content > the content of the column. Allows identifiers for fields of the check result.
